#!/usr/bin/env bash

dir=$(dirname "$0")
normal="$(tput sgr0)"
red="$(tput bold)$(tput setaf 1)"
green="$(tput bold)$(tput setaf 2)"

if lsof -Pi :5000 -sTCP:LISTEN -t >/dev/null ; then
    for file in $(ls $dir/*.json); do
        response=$(curl -s -o /dev/null -w "%{http_code}" \
            -X POST "http://127.0.0.1:5000/screen-video" \
            -H "Content-Type: application/json" \
            -d @$file)
        result=$(test $response = $(cat $file.expected) \
            && echo "${green}Passed${normal}" || echo "${green}Failed${normal}")
        printf "%-40s%s\n" $file $result
    done
else
    echo "${red}Server Not Running${normal}" 1>&2
fi
